version: '3.8'

services:
  ml-service:
    build: ./model_alfa
    container_name: ml_service
    ports:
      - "8000:80"
    networks:
      - app_network

  back-java:
    build: ./back_alfa
    container_name: back_java_service
    ports:
      - "8080:8080"
    networks:
      - app_network

  front-react:
    build: ./front_alfa
    container_name: front_react
    ports:
      - "5000:80"
    networks:
      - app_network

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./back_alfa/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - app_network
    depends_on:
      - back-java

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000" # Expose Grafana UI
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      - app_network
    depends_on:
      - prometheus

networks:
  app_network:
    driver: bridge
